# Python for (open) Neuroscience  
### Practical 2.1 — *Numpy: Arrays, types, indexing*
#### Module 02 - Scientific stack

**How to use this notebook**
- Complete the `____` blanks.
- Keep the starter code structure whenever possible.
- Run each code cell with **Shift+Enter**


In [2]:
import numpy as np
print("numpy version " + np.__version__)

numpy version 2.1.3


### Exercise 1 — Create a 1D array from a list

Convert the Python list below into a NumPy array called `trial_counts`.

Then print:
- the array
- its type
- its dtype

In [3]:
trial_list = [12, 15, 11, 14, 10, 18]
trial_counts = np.array(trial_list)

print(trial_counts)
print(type(trial_counts))
print(trial_counts.dtype)

[12 15 11 14 10 18]
<class 'numpy.ndarray'>
int64


### Exercise 2 — Create a 2D array

Convert the nested list below into a 2D array called `score_matrix`.

Then print:
- the array
- its shape
- its number of dimensions

In [6]:
scores = [[1, 0, 1, 1],
          [0, 1, 1, 0],
          [1, 1, 1, 1]]
score_matrix = np.array(scores)

print(score_matrix)
print(score_matrix.shape)
print(score_matrix.ndim)

[[1 0 1 1]
 [0 1 1 0]
 [1 1 1 1]]
(3, 4)
2


### Exercise 3 — Initialize arrays with fixed values

Create:
- `baseline` as an array of zeros of shape `(4, 6)`
- `mask` as an array of ones of shape `(4, 6)` with dtype `bool`
- `labels` as an array of shape `(2, 3)` filled with the value `7`

In [5]:
baseline = np.zeros((4, 6))
mask = np.ones((4, 6), dtype=bool)
labels = np.full((2, 3), 7)

print(baseline)
print(mask)
print(labels)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[7 7 7]
 [7 7 7]]


### Exercise 4 — Regular sequences

Create:
- `even_values`: all even integers from 0 to 20 included
- `odd_values`: all odd integers from 1 to 19
- `fractions`: 6 equally spaced values from 0 to 1 included

In [10]:
even_values = np.arange(0, 22, 2)
odd_values = np.arange(1, 20, 2) # also here 19 included
fractions = np.linspace(0, 1, 6)

print(even_values)
print(odd_values)
print(fractions)

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]
[0.  0.2 0.4 0.6 0.8 1. ]


### Exercise 5 — Random arrays

Create:
- `int_data`: a `(3, 5)` array of random integers from 0 to 9
- `noise`: a `(2, 4)` array of random values drawn from a normal distribution with mean 0 and standard deviation 1

In [11]:
int_data = np.random.randint(0, 10, size=(3, 5))
noise = np.random.normal(0, 1, size=(2, 4))

print(int_data)
print(noise)

[[1 6 0 6 1]
 [5 0 5 4 0]
 [5 8 9 7 1]]
[[-1.01440297  0.21303845 -1.61646266 -0.95224271]
 [-0.42048976  1.51361801  1.22447605  0.66957776]]


### Exercise 6 — Dtypes and conversion

Create an array called `float_signal` from the list below.

Then:
1. print its dtype
2. convert it to integers and store the result in `int_signal`
3. print both arrays
4. explain briefly what happened to the decimal part

In [17]:
raw_values = [1.7, 2.2, 3.9, 4.1]

float_signal = np.array(raw_values)
print(float_signal)
print(float_signal.dtype)

int_signal = float_signal.astype(int)
print(int_signal)
print(int_signal.dtype)

# What happened to the decimal part?
# Converting an array to integer makes it cut out the decimal part entirely, not even rounding.

[1.7 2.2 3.9 4.1]
float64
[1 2 3 4]
int64


### Exercise 7 — Missing values with `np.nan`

Create a `(3, 4)` array called `missing_block` filled with `np.nan`.

Then replace:
- the entire first row with `0`
- the last column with `1`

In [18]:
missing_block = np.full((3, 4), np.nan)

missing_block[0, :] = 0
missing_block[:, -1] = 1

print(missing_block)

[[ 0.  0.  0.  1.]
 [nan nan nan  1.]
 [nan nan nan  1.]]


### Exercise 8 — Inspect array attributes

Create the array:

```python
arr = np.arange(24).reshape(2, 3, 4)
```

Then print:
- `arr.shape`
- `arr.ndim`
- `arr.size`
- `arr.dtype`

In [19]:
arr = np.arange(24).reshape(2, 3, 4)

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3, 4)
3
24
int64


### Exercise 9 — Converting lists to arrays

Convert the nested list below into a NumPy array called `electrode_grid`.

Then answer:
- what is the shape?
- which axis corresponds to rows?
- which axis corresponds to columns?

In [22]:
grid_list = [[10, 12, 13],
             [9, 11, 14],
             [8, 10, 15],
             [7,  9, 16]]

electrode_grid = np.array(grid_list)

print(electrode_grid.shape)
print(electrode_grid)

# What is the shape? The shape is 3x4
# Which axis is rows? Rows is the 0 axis (4)
# Which axis is columns? Columns is the 1 axis (3)

(4, 3)
[[10 12 13]
 [ 9 11 14]
 [ 8 10 15]
 [ 7  9 16]]


### Exercise 10 — Reshape a 1D array

Create `a = np.arange(18)`.

Then reshape it into:
- `b` with shape `(3, 6)`
- `c` with shape `(2, 3, 3)`

Print all three arrays and their shapes.

In [23]:
a = np.arange(18)

b = a.reshape(3, 6)
c = a.reshape(2, 3, 3)

print(a)
print(a.shape)

print(b)
print(b.shape)

print(c)
print(c.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
(18,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
(3, 6)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
(2, 3, 3)


### Exercise 11 — Decide which reshape is valid

Starting from:

```python
a = np.arange(24)
```

Which of the following reshapes are valid?

- `(4, 6)`
- `(2, 3, 4)`
- `(5, 5)`
- `(2, 12)`

Try them in code. For invalid ones, comment the line and write the reason in markdown.

In [29]:
a = np.arange(24)

valid_1 = a.reshape(4, 6)
valid_2 = a.reshape(2, 3, 4)
valid_3 = a.reshape(2, 12)

print(valid_1)
print(valid_2)
print(valid_3)
print(valid_1.shape)
print(valid_2.shape)
print(valid_3.shape)

# Invalid reshape: invalid = a.reshape(5, 5)
# Why is it invalid? It's invalid because it requires 25 elements but in the array there are only 24 numbers.

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
(4, 6)
(2, 3, 4)
(2, 12)


### Exercise 12 — Basic indexing in 1D

Given:

```python
v = np.arange(10, 110, 10)
```

Extract and print:
- the first element
- the last element
- the third element
- the second-to-last element

In [39]:
v = np.arange(10, 110, 10)

first = v[0]
last = v[-1]
third = v[2]
second_to_last = v[-2]

print(first)
print(last)
print(third)
print(second_to_last)

10
100
30
90


### Exercise 13 — Slicing in 1D

Using the same array `v`, extract:
- the first 4 elements
- the last 3 elements
- every second element
- the reversed array

In [38]:
v = np.arange(10, 110, 10)

first_four = v[:4]
last_three = v[-3:]
every_second = v[::2]
reversed_v = v[::-1]

print(first_four)
print(last_three)
print(every_second)
print(reversed_v)

[10 20 30 40]
[ 80  90 100]
[10 30 50 70 90]
[100  90  80  70  60  50  40  30  20  10]


### Exercise 14 — Integer-array indexing

Given:

```python
v = np.array([10, 20, 30, 40, 50, 60, 70])
```

Use integer indexing to extract:
- the elements at positions `[0, 3, 5]`
- the elements at positions `[6, 2, 1, 2]`

In [37]:
v = np.array([10, 20, 30, 40, 50, 60, 70])

sel_1 = v[[0, 3, 5]]
sel_2 = v[[6, 2, 1, 2]]

print(sel_1)
print(sel_2)

[10 40 60]
[70 30 20 30]


### Exercise 15 — Boolean indexing in 1D

Create a boolean mask that selects values greater than 3 from the array below.

Then use the mask to extract the selected values.

```python
v = np.array([1, 2, 3, 4, 5, 6, 2, 1])
```

In [40]:
v = np.array([1, 2, 3, 4, 5, 6, 2, 1])

mask = v > 3
selected = v[mask]

print(mask)
print(selected)

[False False False  True  True  True False False]
[4 5 6]


### Exercise 16 — Replace values using boolean indexing

Set all negative values in the array below to `np.nan`.

```python
data = np.array([[ 1.2, -0.4,  0.7],
                 [-1.5,  2.1, -0.2],
                 [ 0.3,  0.0, -3.4]])
```

Store the result in a new array without modifying the original one.

In [43]:
data = np.array([[ 1.2, -0.4,  0.7],
                 [-1.5,  2.1, -0.2],
                 [ 0.3,  0.0, -3.4]])

clean = data.astype(float)
clean[clean < 0] = np.nan

print(data)
print(clean)

[[ 1.2 -0.4  0.7]
 [-1.5  2.1 -0.2]
 [ 0.3  0.  -3.4]]
[[1.2 nan 0.7]
 [nan 2.1 nan]
 [0.3 0.  nan]]


### Exercise 17 — Multidimensional indexing

Given:

```python
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
```

Extract and print:
- the element in row 2, column 3
- the entire second row
- the entire first column
- the submatrix made of the first two rows and last two columns

In [44]:
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

elem = m[1, 2]
row_2 = m[1, :]
col_1 = m[:, 0]
sub = m[0:2, 2:4]

print(elem)
print(row_2)
print(col_1)
print(sub)

7
[5 6 7 8]
[1 5 9]
[[3 4]
 [7 8]]


### Exercise 18 — Indexing in 3D

Given:

```python
x = np.arange(24).reshape(2, 3, 4)
```

Extract:
- the shape of `x`
- the element `x[1, 2, 3]`
- all values from the second block (`x[1]`)
- all values from row index 1 across both blocks
- the last column across all blocks and rows

In [46]:
x = np.arange(24).reshape(2, 3, 4)

print(x)
print(x.shape)
print(x[1, 2, 3])
print(x[1, :, :])
print(x[:, 1, :])
print(x[:, :, -1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
23
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 4  5  6  7]
 [16 17 18 19]]
[[ 3  7 11]
 [15 19 23]]


### Exercise 19 — Slices are usually views

Run the code below and explain why both arrays change.

Then rewrite the example using `.copy()` so that only the sliced array changes.

```python
a = np.array([1, 2, 3, 4, 5, 6])
b = a[1:5]
b[0] = 99
print(a)
print(b)
```

In [50]:
a = np.array([1, 2, 3, 4, 5, 6])

# First: reproduce the view behavior
b = a[1:5]
b[0] = 99
print(a)
print(b)

# Then: create an independent copy and modify it
a2 = np.array([1, 2, 3, 4, 5, 6])
b2 = a2[1:5].copy()
b2[0] = 99
print(a2)
print(b2)

[ 1 99  3  4  5  6]
[99  3  4  5]
[1 2 3 4 5 6]
[99  3  4  5]


### Exercise 20 — View behavior in 2D

Create:

```python
img = np.arange(20).reshape(4, 5)
```

Take the slice containing rows 1 to 2 and columns 2 to 4, store it in `patch`, and set all values in `patch` to `-1`.

Print both `img` and `patch`.

Then explain what this tells you about slicing in NumPy.

In [52]:
img = np.arange(20).reshape(4, 5)

patch = img[1:3, 2:4]
patch[:] = -1

print(img)
print(patch)

[[ 0  1  2  3  4]
 [ 5  6 -1 -1  9]
 [10 11 -1 -1 14]
 [15 16 17 18 19]]
[[-1 -1]
 [-1 -1]]


### Exercise 21 — Add singleton dimensions with `np.newaxis`

Start from:

```python
a = np.array([10, 20, 30, 40])
```

Create:
- `row_vec` with shape `(1, 4)`
- `col_vec` with shape `(4, 1)`

Print both arrays and their shapes.

In [55]:
a = np.array([10, 20, 30, 40])

row_vec = a[np.newaxis, :]
col_vec = a[:, np.newaxis]

print(row_vec)
print(row_vec.shape)
print(col_vec)
print(col_vec.shape)

[[10 20 30 40]]
(1, 4)
[[10]
 [20]
 [30]
 [40]]
(4, 1)


### Exercise 22 — Find singleton dimensions

For each array below, print the shape and state which axes are singleton dimensions.

```python
a = np.zeros((5,))
b = np.zeros((1, 5))
c = np.zeros((5, 1, 3))
d = np.zeros((1, 4, 1, 2))
```

In [67]:
a = np.zeros((5,))
b = np.zeros((1, 5))
c = np.zeros((5, 1, 3))
d = np.zeros((1, 4, 1, 2))

print(d)

print("a:", a.shape)
print("b:", b.shape)
print("c:", c.shape)
print("d:", d.shape)

# Which axes are singleton dimensions?
# a: no singleton dimensions
# b: axis 0 is a singleton
# c: axis 1 is a singleton
# d: axis 0 and 2 are singleton dimensions

[[[[0. 0.]]

  [[0. 0.]]

  [[0. 0.]]

  [[0. 0.]]]]
a: (5,)
b: (1, 5)
c: (5, 1, 3)
d: (1, 4, 1, 2)


### Exercise 23 — Mixed challenge: clean and inspect an array

Create a `(4, 5)` array of random integers from `-5` to `9`.

Then:
1. convert it to `float`
2. replace all negative values with `np.nan`
3. print the shape, dtype, and size
4. extract the last two columns
5. extract all non-negative values using boolean indexing

In [68]:
data = np.random.randint(-5, 10, size=(4, 5))

data = data.astype(float)
data[data < 0] = np.nan

print(data)
print(data.shape)
print(data.dtype)
print(data.size)

last_two_cols = data[:, -2:]
non_negative = data[~np.isnan(data)]

print(last_two_cols)
print(non_negative)


[[ 6.  5.  3. nan  8.]
 [ 4.  8.  1.  7.  6.]
 [ 7. nan nan  5.  3.]
 [nan  2. nan nan  8.]]
(4, 5)
float64
20
[[nan  8.]
 [ 7.  6.]
 [ 5.  3.]
 [nan  8.]]
[6. 5. 3. 8. 4. 8. 1. 7. 6. 7. 5. 3. 2. 8.]


### Exercise 24 — Choose the better NumPy solution

You want to select all positive values from an array.

**Option A**
```python
v = np.array([-2, 3, -1, 5, 0, 4])
positive = []
for x in v:
    if x > 0:
        positive.append(x)
positive = np.array(positive)
print(positive)
```

**Option B**
```python
v = np.array([-2, 3, -1, 5, 0, 4])
positive = v[v > 0]
print(positive)
```

Tasks:
1. run both versions
2. verify that they produce the same values
3. decide which one is more idiomatic NumPy for this task
4. write one sentence explaining why

In [73]:
# Option A
v = np.array([-2, 3, -1, 5, 0, 4])
positive_list = []
for x in v:
    if x > 0:
        positive_list.append(x)
positive_a = np.array(positive_list)

# Option B
v = np.array([-2, 3, -1, 5, 0, 4])
positive_b = v[v > 0]

print(positive_a)
print(positive_b)

# Same values?
print(np.array_equal(positive_a,positive_b))

# Add a short markdown answer below: Which solution is more idiomatic NumPy and why?
# Option B is better and more idiomatic because it uses vectorization therefore faster than passing through a for loop.

[3 5 4]
[3 5 4]
True
